Address.create!([
  {street_1: "1510 Blake St", street_2: "", city: "Denver", state: "CO", zip: "80202"},
  {street_1: "1624 Market St", street_2: "", city: "New York", state: "NY", zip: "90210"},
])

Categorization.create!([
  {item_id: 1, category_id: 1},
  {item_id: 2, category_id: 2},
  {item_id: 3, category_id: 3}
  {item_id: 4, category_id: 1},
  {item_id: 5, category_id: 2},
  {item_id: 6, category_id: 3},
  {item_id: 7, category_id: 1},
  {item_id: 8, category_id: 2},
  {item_id: 9, category_id: 3},
  {item_id: 10, category_id: 1},
  {item_id: 11, category_id: 2},
  {item_id: 12, category_id: 3},
  {item_id: 13, category_id: 1},
  {item_id: 14, category_id: 2},
  {item_id: 15, category_id: 3},
  {item_id: 16, category_id: 1},
  {item_id: 16, category_id: 2},
  {item_id: 17, category_id: 3},
  {item_id: 18, category_id: 1},
  {item_id: 19, category_id: 2},
  {item_id: 19, category_id: 3},
  {item_id: 20, category_id: 1},
  {item_id: 21, category_id: 2},
  {item_id: 22, category_id: 3},
  {item_id: 23, category_id: 1},
])

Category.create!([
  {name: "Couch"},
  {name: "Pull Out Couch"},
  {name: "Twin Bed"},
])

Item.create!([
  {title: "Koala Kebabs", description: "Comfortable wood framed futon", price: 2700, max_quantity: 500, scarcity: "endangered", image_file_name: 'http://ipad.wallpaperswiki.com/wp-content/uploads/2012/10/Koala-Bear-Portrait.jpg', image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {title: "Garlic Herb Bald Eagle", description: "Clean pull out couch", price: 177600, max_quantity: 500, scarcity: "endangered", image_file_name: 'http://2.bp.blogspot.com/-ZeWjNkJJBtY/UF9h5OP7ESI/AAAAAAAABFE/57cHP6l4Lsw/s1600/eagle%202.jpg', image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {title: "Octokitty & Chips", description: "Large room with desk and twin bed", price: 133700, max_quantity: 500, scarcity: "endangered", image_file_name: 'http://turpial.org.ve/wp-content/uploads/2012/02/octocat.png', image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {title: "Blue Whale Steak", description: "Quaint futon", price: 1200, max_quantity: 500, scarcity: "endangered", image_file_name: 'http://3.bp.blogspot.com/-LRTwydLLTNs/UHFgm__b9HI/AAAAAAAAEdw/w05ewNaVxKc/s1600/Blue+Whale+Jumping+Out+of+Water.jpg', image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {title: "Wooly Mammoth Burger", description: "Hammock strung up over bathtub", price: 2000, max_quantity: 500, scarcity: "endangered", image_file_name: 'http://1.bp.blogspot.com/-cxUY8vzkBlM/T2AencCFGyI/AAAAAAAABaQ/JOl8xq_eqvI/s1600/wooly_mammoth_model.JPG', image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {title: "Seal Veal Picatta", description: "King size bed",  price: 1400, max_quantity: 500, scarcity: "endangered", image_file_name: 'http://1.bp.blogspot.com/_Npmtn5-O8Uo/S7U86hI3kUI/AAAAAAAAABk/LL59lOfRrcQ/s1600/foca_arpa-1024x768-87398.jpg', image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {title: "Giant Panda Skillet", description: "La-z-boy", price: 8000, max_quantity: 500, scarcity: "endangered", image_file_name: 'http://ipad.wallpaperswiki.com/wp-content/uploads/2012/10/Panda-Climbing.jpg', image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {title: "Capybara Stew", description: "Second floor bedroom", price: 3300, max_quantity: 500, scarcity: "endangered", image_file_name: 'http://ipad.wallpaperswiki.com/wp-content/uploads/2012/10/Capybara-4.jpg', image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {title: "Sloth Ribs", description: "Third floor bedroom with twin bed", price: 3200, max_quantity: 500, scarcity: "endangered", image_file_name: 'http://2.bp.blogspot.com/-DAoY8Y2eBhM/TrEgjbGEgUI/AAAAAAAAAJ0/y8eC_3x2JT4/s400/sloth.jpg', image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {title: "Whooping Crane Sandwich", description: "First floor bedroom with queen", price: 300, max_quantity: 500, scarcity: "endangered", image_file_name: 'http://arvamont.com/photojournal/aransas/IMG_8409.jpg', image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {title: "Braised Canada Lynx Steak", description: "Loft with pull out couch", price: 600, max_quantity: 500, scarcity: "endangered", image_file_name: 'http://www.traveltop.net/wallpapers/2012/05/canadian-lynx-british-columbia-canada-2048x2048.jpg', image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {title: "Humpback Chub Sandwich", description: "Non pull out couch", price: 2400, max_quantity: 500, scarcity: "endangered", image_file_name: 'http://pubs.usgs.gov/fs/2007/3113/images/coverphoto.jpg', image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {title: "Marinated Preble's Meadow Jumping Mouse", description: "Its a couch", price: 700, max_quantity: 500, scarcity: "endangered", image_file_name: 'http://upload.wikimedia.org/wikipedia/commons/2/2c/Apodemus_sylvaticus_(Sardinia).jpg', image_content_type: nil, image_file_size: nil, image_updated_at: nil},
  {title: "Mexican Spotted Owl Tacos", description: "Superman shaped bed", price: 2000, max_quantity: 500, scarcity: "endangered", image_file_name: 'http://upload.wikimedia.org/wikipedia/commons/e/ef/Barred_owl.jpg', image_content_type: nil, image_file_size: nil, image_updated_at: nil},
])
Order.create!([
  {user_id: 1, aasm_state: "cancelled", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 2, aasm_state: "cancelled", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 5, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 4, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 6, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 7, aasm_state: "basket", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 8, aasm_state: "basket", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 3, aasm_state: "basket", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 6, aasm_state: "basket", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 7, aasm_state: "ordered", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 9, aasm_state: "ordered", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 10, aasm_state: "paid", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 11, aasm_state: "paid", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 12, aasm_state: "paid", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 3, aasm_state: "paid", ccn: nil, expdate: nil, card_name: nil},
  {user_id: nil, aasm_state: "basket", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 3, aasm_state: "basket", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 1, aasm_state: "basket", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 2, aasm_state: "ordered", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 4, aasm_state: "ordered", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 5, aasm_state: "ordered", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 4, aasm_state: "ordered", ccn: nil, expdate: nil, card_name: nil}
])
OrderItem.create!([
  {order_id: 2, item_id: 23, quantity: 1},
  {order_id: 3, item_id: 21, quantity: 1},
  {order_id: 3, item_id: 22, quantity: 1},
  {order_id: 3, item_id: 14, quantity: 1},
  {order_id: 4, item_id: 5, quantity: 1},
  {order_id: 4, item_id: 23, quantity: 1},
  {order_id: 4, item_id: 3, quantity: 1},
  {order_id: 5, item_id: 3, quantity: 1},
  {order_id: 5, item_id: 5, quantity: 1},
  {order_id: 5, item_id: 7, quantity: 1},
  {order_id: 17, item_id: 8, quantity: 1},
  {order_id: 17, item_id: 6, quantity: 1},
  {order_id: 18, item_id: 23, quantity: 1},
  {order_id: 18, item_id: 13, quantity: 1},
  {order_id: 19, item_id: 15, quantity: 1},
  {order_id: 19, item_id: 7, quantity: 1},
  {order_id: 12, item_id: 2, quantity: 1},
  {order_id: 14, item_id: 13, quantity: 1},
  {order_id: 14, item_id: 19, quantity: 1},
  {order_id: 5, item_id: 5, quantity: 1},
  {order_id: 5, item_id: 22, quantity: 1},
  {order_id: 6, item_id: 18, quantity: 1},
  {order_id: 16, item_id: 6, quantity: 1},
  {order_id: 7, item_id: 2, quantity: 1},
  {order_id: 11, item_id: 12, quantity: 1},
  {order_id: 1, item_id: 12, quantity: 1},
  {order_id: 18, item_id: 12, quantity: 1},
  {order_id: 18, item_id: 12, quantity: 1},
  {order_id: 1, item_id: 4, quantity: 1},
  {order_id: 2, item_id: 8, quantity: 1},
  {order_id: 3, item_id: 3, quantity: 1},
  {order_id: 14, item_id: 17, quantity: 1},
  {order_id: 4, item_id: 20, quantity: 1},
  {order_id: 19, item_id: 12, quantity: 1},
  {order_id: 19, item_id: 12, quantity: 1},
  {order_id: 20, item_id: 12, quantity: 1},
  {order_id: 16, item_id: 12, quantity: 1},
  {order_id: 18, item_id: 12, quantity: 1},
  {order_id: 12, item_id: 12, quantity: 1}
])
User.create!([
  {first_name: "Rachel",  last_name: "Warbelow",   email: "demo+rachel@jumpstartlab.com", city: "Las Vegas",   state: "Nevada",     password: "password", role: "user"},
  {first_name: "Jorge",   last_name: "Tellez",     email: "demo+jorge@jumpstartlab.com",  city: "San Diego",   state: "California", password: "password", role: "user"},
  {first_name: "Jon",     last_name: "Snow",       email: "jsnow@whitewall.gov",          city: "Hollywood",   state: "California", password: "password", role: "admin"},
  {first_name: "Josh",    last_name: "Cheek",      email: "demo+josh@jumpstartlab.com",   city: "Chicago",     state: "Illinois",   password: "password", role: "admin"},
  {first_name: "Jeff",    last_name: "",           email: "demo+jeff@jumpstartlab.com",   city: "Denver",      state: "Colorado",   password: "password", role: nil},
  {first_name: "Emily",   last_name: "Davis",      email: "emily@email.com",              city: "Kansas City", state: "Missouri",   password: "password", role: nil},
  {first_name: "Will",    last_name: "Faurot",     email: "will@email.com",               city: "Denver",      state: "Colorado",   password: "password", role: nil},
  {first_name: "Gustavo", last_name: "Villagrana", email: "gustavo@email.com",            city: "Austin",      state: "Texas",      password: "password", role: nil},
  {first_name: "Marc",    last_name: "Garreau",    email: "marc@email.com",               city: "Orlando",     state: "Florida",    password: "password", role: nil},
  {first_name: "Eric",    last_name: "Fransen",    email: "eric@email.com",               city: "St. Louis",   state: "Missouri",   password: "password", role: nil},
  {first_name: "name",    last_name: "name",       email: "abcde@123.com",                city: "Portland",    state: "Oregon",     password: "password", role: nil},
  {first_name: "Bald",    last_name: "Eagle",      email: "bald@eagle.com",               city: "Dayton",      state: "Ohio",       password: "password", role: nil}
])
