Address.create!([
  {street_1: "1624 Market St", street_2: "", city: "Denver", state: "CO", zip: "80202", item_id: 1},
  {street_1: "1510 Blake St", street_2: "", city: "Denver", state: "CO", zip: "80202", item_id: 2},
  {street_1: "797 W 29th Ave", street_2: "", city: "Denver", state: "CO", zip: "80202", item_id: 3},
  {street_1: "1215 15th St", street_2: "", city: "Denver", state: "CO", zip: "80202", item_id: 4},
  {street_1: "1510 Blake St", street_2: "", city: "Denver", state: "CO", zip: "80202", item_id: 5},
  {street_1: "1062 Deleware St", street_2: "", city: "Denver", state: "CO", zip: "80204", item_id: 6},
  {street_1: "2030 W 30th Ave", street_2: "", city: "Denver", state: "CO", zip: "80211", item_id: 7},
  {street_1: "3400 Navajo St", street_2: "", city: "Denver", state: "CO", zip: "80211", item_id: 8},
  {street_1: "275 South Cherokee St", street_2: "", city: "Denver", state: "CO", zip: "80223", item_id: 9},
  {street_1: "150 Clayton Lane", street_2: "", city: "Denver", state: "CO", zip: "80206", item_id: 10},
  {street_1: "2191 Arapahoe St", street_2: "", city: "Denver", state: "CO", zip: "80205", item_id: 11},
  {street_1: "3090 Downing St", street_2: "", city: "Denver", state: "CO", zip: "80205", item_id: 12},
  {street_1: "2300 Steele St", street_2: "", city: "Denver", state: "CO", zip: "80205", item_id: 13},
  {street_1: "1835 Franklin St", street_2: "", city: "Denver", state: "CO", zip: "80218", item_id: 14},

  {street_1: "1624 Market St", street_2: "", city: "New York", state: "NY", zip: "80202", item_id: 15},
  {street_1: "1510 Blake St", street_2: "", city: "New York", state: "NY", zip: "80202", item_id: 16},
  {street_1: "797 W 29th Ave", street_2: "", city: "New York", state: "NY", zip: "80202", item_id: 17},
  {street_1: "1215 15th St", street_2: "", city: "New York", state: "NY", zip: "80202", item_id: 18},
  {street_1: "1510 Blake St", street_2: "", city: "New York", state: "NY", zip: "80202", item_id: 19},
  {street_1: "1062 Deleware St", street_2: "", city: "New York", state: "NY", zip: "80204", item_id: 20},
  {street_1: "2030 W 30th Ave", street_2: "", city: "New York", state: "NY", zip: "80211", item_id: 21},
  {street_1: "3400 Navajo St", street_2: "", city: "New York", state: "NY", zip: "80211", item_id: 22},
  {street_1: "275 South Cherokee St", street_2: "", city: "New York", state: "NY", zip: "80223", item_id: 23},
  {street_1: "150 Clayton Lane", street_2: "", city: "New York", state: "NY", zip: "80206", item_id: 24},
  {street_1: "2191 Arapahoe St", street_2: "", city: "New York", state: "NY", zip: "80205", item_id: 25},
  {street_1: "3090 Downing St", street_2: "", city: "New York", state: "NY", zip: "80205", item_id: 26},
  {street_1: "2300 Steele St", street_2: "", city: "New York", state: "NY", zip: "80205", item_id: 27},
  {street_1: "1835 Franklin St", street_2: "", city: "New York", state: "NY", zip: "80218", item_id: 28},
  {street_1: "2233 Franklin St", street_2: "", city: "New York", state: "CO", zip: "80218", item_id: 29},
  {street_1: "332 Gustavo Ave", street_2: "", city: "New York", state: "CA", zip: "80218", item_id: 30},
  {street_1: "2211 Emily Lane", street_2: "", city: "New York", state: "CA", zip: "80218", item_id: 31},
  {street_1: "3344 Run DMC", street_2: "", city: "New York", state: "CA", zip: "80218", item_id: 32},
  {street_1: "1835 Frank Lane", street_2: "", city: "New York", state: "CA", zip: "80218", item_id: 33},

])

Categorization.create!([
  {item_id: 1,  category_id: 1},
  {item_id: 2,  category_id: 2},
  {item_id: 3,  category_id: 3},
  {item_id: 4,  category_id: 1},
  {item_id: 5,  category_id: 2},
  {item_id: 6,  category_id: 3},
  {item_id: 7,  category_id: 1},
  {item_id: 8,  category_id: 2},
  {item_id: 9,  category_id: 3},
  {item_id: 10, category_id: 1},
  {item_id: 11, category_id: 2},
  {item_id: 12, category_id: 3},
  {item_id: 13, category_id: 1},
  {item_id: 14, category_id: 2}
])

Category.create!([
  {name: "Couch"},
  {name: "Shared Room"},
  {name: "Private Room"},
  {name: "Whole Place"}
])

Item.create!([
  {title: "The Humble Abode", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 27000,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 1, accommodation: "Private Room" },
  {title: "300 sq ft room", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price:         19000,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 1, accommodation: "Private Room" },
  {title: "Cozy Bungalow in Rose", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price:  14000,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 1, accommodation: "Shared Room" },
  {title: "NW Nob Hill Serene", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price:     17400, max_quantity: 500, scarcity: "endangered", people_per_unit: 2, bathroom: "Shared",  user_id: 2, accommodation: "Private Room" },
  {title: "Quiet place!", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price:           17700, max_quantity: 500, scarcity: "endangered", people_per_unit: 2, bathroom: "Shared",  user_id: 2, accommodation: "Whole Place" },
  {title: "Room in West Town", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price:      230000, max_quantity: 500, scarcity: "endangered", people_per_unit: 2, bathroom: "Shared",  user_id: 2, accommodation: "Shared Room" },
  {title: "Downtown Logan Square", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 17400, max_quantity: 500, scarcity: "endangered", people_per_unit: 2, bathroom: "Shared",  user_id: 3, accommodation: "Couch" },
  {title: "Private Apartment", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price:   5900, max_quantity: 500, scarcity: "endangered", people_per_unit: 2, bathroom: "Shared",  user_id: 3, accommodation: "Private Room" },
  {title: "Lovely 1-bdrm", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price:       8900, max_quantity: 500, scarcity: "endangered", people_per_unit: 2, bathroom: "Shared",  user_id: 3, accommodation: "Shared Room" },
  {title: "2BR in Logan Square", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 5000, max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 4, accommodation: "Whole Place" },
  {title: "Cozy Cutie in Caphill", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",price:12000, max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 4, accommodation: "Private Room" },
  {title: "Josh's Futon", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price:        11000, max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 4, accommodation: "Private Room" },
  {title: "Countryside Vintage Suite", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 25000, max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 4, accommodation: "Whole Place" },
  {title: "Uptown Suite", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 1200,   max_quantity: 500, scarcity: "endangered", people_per_unit: 2, bathroom: "Private", user_id: 5, accommodation: "Private Room" },
  {title: "Close to Downtown", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 14000,   max_quantity: 500, scarcity: "endangered", people_per_unit: 2, bathroom: "Private", user_id: 5, accommodation: "Private Room" },
  {title: "Historic Highlands House!", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 21000,   max_quantity: 500, scarcity: "endangered", people_per_unit: 2, bathroom: "Private", user_id: 5, accommodation: "Whole Place" },
  {title: "It's a Farm!", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 1500,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Shared",  user_id: 6, accommodation: "Whole Place" },
  {title: "Modern Cap Hill 1BR", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 1400,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Shared",  user_id: 6, accommodation: "Whole Place" },
  {title: "Denver - Highland Home", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 27000,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Shared",  user_id: 6, accommodation: "Shared Room" },
  {title: "Room in Congress Park", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 30000,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Shared",  user_id: 6, accommodation: "Private Room" },
  {title: "Shared Room in Cap Hill",        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 13000,   max_quantity: 500, scarcity: "endangered", people_per_unit: 2, bathroom: "Shared",  user_id: 7, accommodation: "Shared Room" },
  {title: "Luxury in the City",           description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 25000,   max_quantity: 500, scarcity: "endangered", people_per_unit: 2, bathroom: "Shared",  user_id: 7, accommodation: "Couch" },
  {title: "Historic Loft in Lodo",       description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 8900,   max_quantity: 500, scarcity: "endangered", people_per_unit: 2, bathroom: "Shared",  user_id: 7, accommodation: "Shared Room" },
  {title: "Close to Everything!",     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 7000,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 8, accommodation: "Couch" },
  {title: "Modern Apt in Highlands",        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 14000,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 8, accommodation: "Private Room" },
  {title: "Historic Urban Loft", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 1700,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 8, accommodation: "Whole Place" },
  {title: "Luxury Lo-hi Loft",       description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 18900,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 10, accommodation: "Private Room" },
  {title: "Private Basement - Clean",           description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 11000,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 10, accommodation: "Private Room" },
  {title: "Denver - Congress Park",     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 6400,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 10, accommodation: "Whole Place" },
  {title: "Awesome Cupboard Bed",           description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 9000,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 10, accommodation: "Shared Room" },
  {title: "Mid-century across Lake!",           description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 2400,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 9, accommodation: "Private Room" },
  {title: "Shared BR in Cap Hill",        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 1800,   max_quantity: 500, scarcity: "endangered", people_per_unit: 1, bathroom: "Private", user_id: 9, accommodation: "Shared Room" },
  {title: "Sunny Home Curtis Park",     description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.", price: 2000,   max_quantity: 500, scarcity: "endangered", people_per_unit: 4, bathroom: "Shared",  user_id: 19, accommodation: "Private Room" }
])

ItemAvailability.create!([
  {item_id: 1, availability_id: 1},
  {item_id: 1, availability_id: 2},
  {item_id: 1, availability_id: 3},
  {item_id: 1, availability_id: 4},
  {item_id: 1, availability_id: 5},
  {item_id: 1, availability_id: 6},
  {item_id: 2, availability_id: 7},
  {item_id: 2, availability_id: 8},
  {item_id: 2, availability_id: 9},
  {item_id: 2, availability_id: 10},
  {item_id: 2, availability_id: 11},
  {item_id: 3, availability_id: 12},
  {item_id: 3, availability_id: 13},
  {item_id: 3, availability_id: 14},
  {item_id: 3, availability_id: 15},
  {item_id: 3, availability_id: 16},
  {item_id: 4, availability_id: 17},
  {item_id: 4, availability_id: 18},
  {item_id: 4, availability_id: 19},
  {item_id: 4, availability_id: 20},
  {item_id: 4, availability_id: 21},
  {item_id: 5, availability_id: 22},
  {item_id: 5, availability_id: 23},
  {item_id: 5, availability_id: 24},
  {item_id: 5, availability_id: 25},
  {item_id: 5, availability_id: 26},
  {item_id: 6, availability_id: 27},
  {item_id: 6, availability_id: 28},
  {item_id: 6, availability_id: 29},
  {item_id: 6, availability_id: 30},
  {item_id: 6, availability_id: 31},
  {item_id: 7, availability_id: 32},
  {item_id: 7, availability_id: 33},
  {item_id: 7, availability_id: 34},
  {item_id: 7, availability_id: 35},
  {item_id: 7, availability_id: 36},
  {item_id: 8, availability_id: 37},
  {item_id: 8, availability_id: 38},
  {item_id: 8, availability_id: 39},
  {item_id: 8, availability_id: 40},
  {item_id: 8, availability_id: 41},
  {item_id: 9, availability_id: 42},
  {item_id: 9, availability_id: 43},
  {item_id: 9, availability_id: 44},
  {item_id: 9, availability_id: 45},
  {item_id: 9, availability_id: 46},
  {item_id: 10, availability_id: 47},
  {item_id: 10, availability_id: 48},
  {item_id: 10, availability_id: 49},
  {item_id: 10, availability_id: 50},
  {item_id: 10, availability_id: 51},
  {item_id: 11, availability_id: 52},
  {item_id: 11, availability_id: 53},
  {item_id: 11, availability_id: 54},
  {item_id: 11, availability_id: 55},
  {item_id: 11, availability_id: 56},
  {item_id: 12, availability_id: 57},
  {item_id: 12, availability_id: 58},
  {item_id: 12, availability_id: 59},
  {item_id: 12, availability_id: 60},
  {item_id: 12, availability_id: 61},
  {item_id: 13, availability_id: 62},
  {item_id: 13, availability_id: 63},
  {item_id: 13, availability_id: 64},
  {item_id: 13, availability_id: 65},
  {item_id: 13, availability_id: 66},
  {item_id: 14, availability_id: 67},
  {item_id: 14, availability_id: 68},
  {item_id: 14, availability_id: 69},
  {item_id: 14, availability_id: 70},
  {item_id: 14, availability_id: 71},
  {item_id: 15, availability_id: 72},
  {item_id: 15, availability_id: 73},
  {item_id: 15, availability_id: 74},
  {item_id: 15, availability_id: 75},
  {item_id: 15, availability_id: 76},
  {item_id: 16, availability_id: 77},
  {item_id: 16, availability_id: 78},
  {item_id: 16, availability_id: 79},
  {item_id: 16, availability_id: 80},
  {item_id: 16, availability_id: 81},
  {item_id: 17, availability_id: 82},
  {item_id: 17, availability_id: 83},
  {item_id: 17, availability_id: 84},
  {item_id: 17, availability_id: 85},
  {item_id: 17, availability_id: 86},
  {item_id: 18, availability_id: 87},
  {item_id: 18, availability_id: 88},
  {item_id: 18, availability_id: 89},
  {item_id: 18, availability_id: 90},
  {item_id: 18, availability_id: 91},
  {item_id: 19, availability_id: 92},
  {item_id: 19, availability_id: 93},
  {item_id: 19, availability_id: 94},
  {item_id: 19, availability_id: 95},
  {item_id: 19, availability_id: 96},
  {item_id: 20, availability_id: 97},
  {item_id: 20, availability_id: 98},
  {item_id: 20, availability_id: 99},
  {item_id: 20, availability_id: 100},
  {item_id: 20, availability_id: 101},
  {item_id: 21, availability_id: 102},
  {item_id: 21, availability_id: 103},
  {item_id: 21, availability_id: 104},
  {item_id: 21, availability_id: 105},
  {item_id: 21, availability_id: 106},
  {item_id: 22, availability_id: 107},
  {item_id: 22, availability_id: 108},
  {item_id: 22, availability_id: 109},
  {item_id: 22, availability_id: 110},
  {item_id: 22, availability_id: 111},
  {item_id: 23, availability_id: 112},
  {item_id: 23, availability_id: 113},
  {item_id: 23, availability_id: 114},
  {item_id: 23, availability_id: 115},
  {item_id: 23, availability_id: 116},
  {item_id: 24, availability_id: 117},
  {item_id: 24, availability_id: 118},
  {item_id: 24, availability_id: 119},
  {item_id: 24, availability_id: 120},
  {item_id: 24, availability_id: 121},
  {item_id: 25, availability_id: 122},
  {item_id: 25, availability_id: 123},
  {item_id: 25, availability_id: 124},
  {item_id: 25, availability_id: 125},
  {item_id: 25, availability_id: 126},
  {item_id: 26, availability_id: 127},
  {item_id: 26, availability_id: 128},
  {item_id: 26, availability_id: 129},
  {item_id: 26, availability_id: 130},
  {item_id: 26, availability_id: 131},
  {item_id: 27, availability_id: 132},
  {item_id: 27, availability_id: 133},
  {item_id: 27, availability_id: 134},
  {item_id: 27, availability_id: 135},
  {item_id: 27, availability_id: 136},
  {item_id: 28, availability_id: 137},
  {item_id: 28, availability_id: 138},
  {item_id: 28, availability_id: 139},
  {item_id: 28, availability_id: 140},
  {item_id: 28, availability_id: 141},
  {item_id: 29, availability_id: 142},
  {item_id: 29, availability_id: 143},
  {item_id: 29, availability_id: 144},
  {item_id: 29, availability_id: 145},
  {item_id: 29, availability_id: 146},
  {item_id: 30, availability_id: 147},
  {item_id: 30, availability_id: 148},
  {item_id: 30, availability_id: 149},
  {item_id: 30, availability_id: 150},
  {item_id: 30, availability_id: 151},
  {item_id: 31, availability_id: 152},
  {item_id: 31, availability_id: 153},
  {item_id: 31, availability_id: 154},
  {item_id: 31, availability_id: 155},
  {item_id: 31, availability_id: 156},
  {item_id: 32, availability_id: 157},
  {item_id: 32, availability_id: 158},
  {item_id: 32, availability_id: 159},
  {item_id: 32, availability_id: 160},
  {item_id: 32, availability_id: 161},
  {item_id: 33, availability_id: 162},
  {item_id: 33, availability_id: 163},
  {item_id: 33, availability_id: 164},
  {item_id: 33, availability_id: 165},
  {item_id: 33, availability_id: 166}
  ])

Availability.create!([
  {date:"03/10/2014", order_item_id: nil},
  {date:"04/10/2014", order_item_id: nil},
  {date:"05/10/2014", order_item_id: nil},
  {date:"10/10/2014", order_item_id: nil},
  {date:"11/10/2014", order_item_id: nil},
  {date:"12/10/2014", order_item_id: nil},
  {date:"10/10/2014", order_item_id: nil},
  {date:"11/10/2014", order_item_id: nil},
  {date:"12/10/2014", order_item_id: nil},
  {date:"11/10/2014", order_item_id: 1},
  {date:"12/10/2014", order_item_id: 1},
  {date:"10/10/2014", order_item_id: 2},
  {date:"11/10/2014", order_item_id: 2},
  {date:"12/10/2014", order_item_id: 2},
  {date:"04/10/2014", order_item_id: 3},
  {date:"04/10/2014", order_item_id: 4},
  {date:"03/10/2014", order_item_id: 5},
  {date:"04/10/2014", order_item_id: 5},
  {date:"10/10/2014", order_item_id: 6},
  {date:"11/10/2014", order_item_id: 6},
  {date:"12/10/2014", order_item_id: 6},
  {date:"04/10/2014", order_item_id: 7},
  {date:"11/10/2014", order_item_id: 8},
  {date:"11/10/2014", order_item_id: 9},
  {date:"12/10/2014", order_item_id: 10},
  {date:"10/10/2014", order_item_id: 11},
  {date:"11/10/2014", order_item_id: 11},
  {date:"12/10/2014", order_item_id: 11},
  {date:"11/10/2014", order_item_id: 12},
  {date:"12/10/2014", order_item_id: 12},
  {date:"04/10/2014", order_item_id: 13},
  {date:"12/10/2014", order_item_id: 14},
  {date:"10/10/2014", order_item_id: 15},
  {date:"11/10/2014", order_item_id: 15},
  {date:"12/10/2014", order_item_id: 16},
  {date:"12/10/2014", order_item_id: 16},
  {date:"17/10/2014", order_item_id: 17},
  {date:"18/10/2014", order_item_id: 17},
  {date:"17/10/2014", order_item_id: 18},
  {date:"10/10/2014", order_item_id: 19},
  {date:"11/10/2014", order_item_id: 19},
  {date:"12/10/2014", order_item_id: 19},
  {date:"18/10/2014", order_item_id: 20},
  {date:"03/10/2014", order_item_id: 21},
  {date:"04/10/2014", order_item_id: 21},
  {date:"12/10/2014", order_item_id: 22},
  {date:"24/10/2014", order_item_id: 23},
  {date:"24/10/2014", order_item_id: 24},
  {date:"02/10/2014", order_item_id: 25},
  {date:"11/10/2014", order_item_id: 26},
  {date:"12/10/2014", order_item_id: 26},
  {date:"22/10/2014", order_item_id: 27},
  {date:"23/10/2014", order_item_id: 27},
  {date:"24/10/2014", order_item_id: 27},
  {date:"25/10/2014", order_item_id: 27},
  {date:"11/10/2014", order_item_id: 28},
  {date:"03/10/2014", order_item_id: 29},
  {date:"10/10/2014", order_item_id: 30},
  {date:"11/10/2014", order_item_id: 30},
  {date:"12/10/2014", order_item_id: 30},
  {date:"23/10/2014", order_item_id: 31},
  {date:"24/10/2014", order_item_id: 31},
  {date:"17/10/2014", order_item_id: 32},
  {date:"11/10/2014", order_item_id: 33},
  {date:"11/10/2014", order_item_id: 34},
  {date:"12/10/2014", order_item_id: 34},
  {date:"24/10/2014", order_item_id: 35},
  {date:"25/10/2014", order_item_id: 36},
  {date:"12/10/2014", order_item_id: 37},
  {date:"11/10/2014", order_item_id: 38},
  {date:"12/10/2014", order_item_id: 38},
  {date:"13/10/2014", order_item_id: 38},
  {date:"26/10/2014", order_item_id: 39},
  {date:"24/10/2014", order_item_id: 40},
  {date:"25/10/2014", order_item_id: 40},
  {date:"10/10/2014", order_item_id: 41},
  {date:"11/10/2014", order_item_id: 41},
  {date:"03/10/2014", order_item_id: 42},
  {date:"04/10/2014", order_item_id: 43},
  {date:"05/10/2014", order_item_id: 44},
  {date:"11/10/2014", order_item_id: 45},
  {date:"12/10/2014", order_item_id: 45},
  {date:"24/10/2014", order_item_id: 46},
  {date:"25/10/2014", order_item_id: 46},
  {date:"12/10/2014", order_item_id: 47},
  {date:"17/10/2014", order_item_id: 48},
  {date:"18/10/2014", order_item_id: 48},
  {date:"23/10/2014", order_item_id: 49},
  {date:"24/10/2014", order_item_id: 49},
  {date:"25/10/2014", order_item_id: 49},
  {date:"22/10/2014", order_item_id: nil},
  {date:"23/10/2014", order_item_id: nil},
  {date:"24/10/2014", order_item_id: nil},
  {date:"25/10/2014", order_item_id: nil},
  {date:"26/10/2014", order_item_id: nil},
  {date:"27/10/2014", order_item_id: nil},
  {date:"28/10/2014", order_item_id: nil},
  {date:"13/10/2014", order_item_id: nil},
  {date:"14/10/2014", order_item_id: nil},
  {date:"15/10/2014", order_item_id: nil},
  {date:"16/10/2014", order_item_id: nil},
  {date:"22/10/2014", order_item_id: 53},
  {date:"23/10/2014", order_item_id: 53},
  {date:"24/10/2014", order_item_id: 53},
  {date:"14/10/2014", order_item_id: nil},
  {date:"15/10/2014", order_item_id: nil},
  {date:"16/10/2014", order_item_id: 54},
  {date:"05/10/2014", order_item_id: 55},
  {date:"06/10/2014", order_item_id: 55},
  {date:"15/10/2014", order_item_id: 56},
  {date:"16/10/2014", order_item_id: nil},
  {date:"17/10/2014", order_item_id: nil},
  {date:"22/10/2014", order_item_id: nil},
  {date:"23/10/2014", order_item_id: nil},
  {date:"06/10/2014", order_item_id: nil},
  {date:"07/10/2014", order_item_id: nil},
  {date:"08/10/2014", order_item_id: nil},
  {date:"09/10/2014", order_item_id: nil},
  {date:"10/10/2014", order_item_id: nil},
  {date:"24/10/2014", order_item_id: 60},
  {date:"25/10/2014", order_item_id: 60},
  {date:"26/10/2014", order_item_id: 60},
  {date:"24/10/2014", order_item_id: nil},
  {date:"25/10/2014", order_item_id: nil},
  {date:"26/10/2014", order_item_id: nil},
  {date:"27/10/2014", order_item_id: nil},
  {date:"28/10/2014", order_item_id: nil},
  {date:"10/10/2014", order_item_id: nil},
  {date:"11/10/2014", order_item_id: nil},
  {date:"12/10/2014", order_item_id: nil},
  {date:"23/10/2014", order_item_id: 63},
  {date:"24/10/2014", order_item_id: 63},
  {date:"17/10/2014", order_item_id: 64},
  {date:"11/10/2014", order_item_id: 65},
  {date:"11/10/2014", order_item_id: nil},
  {date:"12/10/2014", order_item_id: nil},
  {date:"24/10/2014", order_item_id: nil},
  {date:"25/10/2014", order_item_id: nil},
  {date:"12/10/2014", order_item_id: 68},
  {date:"11/10/2014", order_item_id: nil},
  {date:"12/10/2014", order_item_id: nil},
  {date:"13/10/2014", order_item_id: nil},
  {date:"26/10/2014", order_item_id: 70},
  {date:"24/10/2014", order_item_id: 71},
  {date:"25/10/2014", order_item_id: 71},
  {date:"10/10/2014", order_item_id: 72},
  {date:"11/10/2014", order_item_id: 72},
  {date:"03/10/2014", order_item_id: nil},
  {date:"04/10/2014", order_item_id: nil},
  {date:"05/10/2014", order_item_id: nil},
  {date:"11/10/2014", order_item_id: 74},
  {date:"12/10/2014", order_item_id: 74},
  {date:"24/10/2014", order_item_id: 75},
  {date:"25/10/2014", order_item_id: 75},
  {date:"12/10/2014", order_item_id: 76},
  {date:"17/10/2014", order_item_id: 76},
  {date:"18/10/2014", order_item_id: 76},
  {date:"23/10/2014", order_item_id: nil},
  {date:"24/10/2014", order_item_id: nil},
  {date:"25/10/2014", order_item_id: nil},
  {date:"10/10/2014", order_item_id: nil},
  {date:"11/10/2014", order_item_id: nil},
  {date:"12/10/2014", order_item_id: nil},
  {date:"23/10/2014", order_item_id: 79},
  {date:"24/10/2014", order_item_id: 79},
  {date:"17/10/2014", order_item_id: 80},
  {date:"11/10/2014", order_item_id: 81},
  {date:"11/10/2014", order_item_id: nil},
  {date:"12/10/2014", order_item_id: nil},
  {date:"24/10/2014", order_item_id: nil},
  {date:"25/10/2014", order_item_id: nil},
  {date:"12/10/2014", order_item_id: 84},
  {date:"11/10/2014", order_item_id: nil},
  {date:"12/10/2014", order_item_id: nil},
  {date:"13/10/2014", order_item_id: nil},
  {date:"26/10/2014", order_item_id: 86},
  {date:"24/10/2014", order_item_id: nil},
  {date:"25/10/2014", order_item_id: nil},
  {date:"10/10/2014", order_item_id: 88},
  {date:"11/10/2014", order_item_id: 88},
  {date:"03/10/2014", order_item_id: nil},
  {date:"04/10/2014", order_item_id: nil},
  {date:"05/10/2014", order_item_id: nil},
  {date:"11/10/2014", order_item_id: 90},
  {date:"12/10/2014", order_item_id: 91},
  {date:"24/10/2014", order_item_id: nil},
  {date:"25/10/2014", order_item_id: nil},
  {date:"12/10/2014", order_item_id: 93},
  {date:"17/10/2014", order_item_id: 94},
  {date:"18/10/2014", order_item_id: 94},
  {date:"23/10/2014", order_item_id: nil},
  {date:"24/10/2014", order_item_id: nil},
  {date:"25/10/2014", order_item_id: nil}
  ])

Order.create!([
  {user_id: 1,  aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 1,  aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 1,  aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 2,  aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 2,  aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 3,  aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 4,  aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 4,  aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 5,  aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 5,  aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 6,  aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 6,  aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 6,  aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 6,  aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 7,  aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 8,  aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 8,  aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 9,  aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 9,  aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 9,  aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 10, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 11, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 12, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 13, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 14, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 14, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 15, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 16, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 17, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 17, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 18, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 18, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 18, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 19, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 20, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 21, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 22, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 22, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 23, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 24, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 25, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 26, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 27, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 27, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 30, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 30, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 31, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 32, aasm_state: "completed", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 32, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
  {user_id: 32, aasm_state: "requested", ccn: nil, expdate: nil, card_name: nil},
])

OrderItem.create!([
  {order_id: 1,  item_id: 17},
  {order_id: 1,  item_id: 4},
  {order_id: 2,  item_id: 6},
  {order_id: 3,  item_id: 10},
  {order_id: 3,  item_id: 18},
  {order_id: 4,  item_id: 33},
  {order_id: 4,  item_id: 15},
  {order_id: 5,  item_id: 27},
  {order_id: 5,  item_id: 2},
  {order_id: 6,  item_id: 13},
  {order_id: 7,  item_id: 22},
  {order_id: 8,  item_id: 18},
  {order_id: 9,  item_id: 17},
  {order_id: 9,  item_id: 6},
  {order_id: 10, item_id: 18},
  {order_id: 11, item_id: 19},
  {order_id: 12, item_id: 3},
  {order_id: 12, item_id: 6},
  {order_id: 12, item_id: 2},
  {order_id: 13, item_id: 23},
  {order_id: 14, item_id: 30},
  {order_id: 14, item_id: 9},
  {order_id: 15, item_id: 1},
  {order_id: 16, item_id: 3},
  {order_id: 16, item_id: 10},
  {order_id: 17, item_id: 2},
  {order_id: 18, item_id: 16},
  {order_id: 18, item_id: 17},
  {order_id: 19, item_id: 12},
  {order_id: 20, item_id: 12},
  {order_id: 21, item_id: 4},
  {order_id: 21, item_id: 19},
  {order_id: 22, item_id: 2},
  {order_id: 23, item_id: 16},
  {order_id: 24, item_id: 17},
  {order_id: 24, item_id: 10},
  {order_id: 25, item_id: 12},
  {order_id: 25, item_id: 16},
  {order_id: 26, item_id: 5},
  {order_id: 27, item_id: 3},
  {order_id: 27, item_id: 16},
  {order_id: 27, item_id: 25},
  {order_id: 28, item_id: 29},
  {order_id: 29, item_id: 25},
  {order_id: 29, item_id: 32},
  {order_id: 30, item_id: 6},
  {order_id: 31, item_id: 16},
  {order_id: 31, item_id: 1},
  {order_id: 32, item_id: 18}
])

ItemImage.create!([
  {image: File.new("#{Rails.root}/spec/fixtures/bedroom.jpg"), item_id: 1},
  {image: File.new("#{Rails.root}/spec/fixtures/New-bedroom.jpg"), item_id: 1},
  {image: File.new("#{Rails.root}/spec/fixtures/house-modern-wood.jpg"), item_id: 2},
  {image: File.new("#{Rails.root}/spec/fixtures/house-linus-2707.jpg"), item_id: 3},
  {image: File.new("#{Rails.root}/spec/fixtures/forest-house-idyllic.jpg"), item_id: 4},
  {image: File.new("#{Rails.root}/spec/fixtures/dark-clouds-hills-lighthouse.jpg"), item_id: 5},
  {image: File.new("#{Rails.root}/spec/fixtures/balcony-house-window.jpg"), item_id: 6},
  {image: File.new("#{Rails.root}/spec/fixtures/bricks-building-fire-escape.jpg"), item_id: 7},
  {image: File.new("#{Rails.root}/spec/fixtures/beach-building-house.jpg"), item_id: 8},
  {image: File.new("#{Rails.root}/spec/fixtures/bedroom-hostel-hotel.jpg"), item_id: 9},
  {image: File.new("#{Rails.root}/spec/fixtures/beetle-car-classic.jpg"), item_id: 10},
  {image: File.new("#{Rails.root}/spec/fixtures/bed-bedroom.jpg"), item_id: 11},
  {image: File.new("#{Rails.root}/spec/fixtures/bedroom-small.jpg"), item_id: 12},
  {image: File.new("#{Rails.root}/spec/fixtures/barn-countryside-field.jpg"), item_id: 13},
  {image: File.new("#{Rails.root}/spec/fixtures/bedroom.jpg"), item_id: 14},
  {image: File.new("#{Rails.root}/spec/fixtures/destroyed-facade-house.jpg"), item_id: 15},
  {image: File.new("#{Rails.root}/spec/fixtures/bricks-apartment.jpg"), item_id: 16},
  {image: File.new("#{Rails.root}/spec/fixtures/avenue-branches-farm.jpg"), item_id: 17},
  {image: File.new("#{Rails.root}/spec/fixtures/Guest-bed5.jpg"), item_id: 18},
  {image: File.new("#{Rails.root}/spec/fixtures/bedroom-designs-387.jpg"), item_id: 19},
  {image: File.new("#{Rails.root}/spec/fixtures/bedroom-furniture-7.jpg"), item_id: 20},
  {image: File.new("#{Rails.root}/spec/fixtures/Contemporary-bedroom-scheme.jpeg"), item_id: 21},
  {image: File.new("#{Rails.root}/spec/fixtures/Double-master-bedroom.jpg"), item_id: 22},
  {image: File.new("#{Rails.root}/spec/fixtures/retro-bedroom-design.jpg"), item_id: 23},
  {image: File.new("#{Rails.root}/spec/fixtures/Swanky-guest-room.jpg"), item_id: 24},
  {image: File.new("#{Rails.root}/spec/fixtures/Sweet-ass-bunks.jpg"), item_id: 25},
  {image: File.new("#{Rails.root}/spec/fixtures/Contemporary-bedroom.jpg"), item_id: 26},
  {image: File.new("#{Rails.root}/spec/fixtures/Coral.jpg"), item_id: 27},
  {image: File.new("#{Rails.root}/spec/fixtures/Guest_office.jpeg"), item_id: 28},
  {image: File.new("#{Rails.root}/spec/fixtures/Guest_room_1.jpg"), item_id: 29},
  {image: File.new("#{Rails.root}/spec/fixtures/Harry-bad-ass-cupboard-bed.jpg"), item_id: 30},
  {image: File.new("#{Rails.root}/spec/fixtures/Guest-room-6.gif"), item_id: 31},
  {image: File.new("#{Rails.root}/spec/fixtures/Guest-room18.JPG"), item_id: 32},
  {image: File.new("#{Rails.root}/spec/fixtures/New-bedroom.jpg"), item_id: 33}
])

User.create!([
  {first_name: "Rachel",     last_name: "Warbelow",   email: "demo+rachel@jumpstartlab.com", city: "Las Vegas",        state: "Nevada",       password: "password", role: "user"},
  {first_name: "Jorge",      last_name: "Tellez",     email: "demo+jorge@jumpstartlab.com",  city: "San Diego",        state: "California",   password: "password", role: "user"},
  {first_name: "Steve",      last_name: "Kinney",     email: "demo+steve@jumpstartlab.com",  city: "New York",         state: "New York",     password: "password", role: "admin"},
  {first_name: "Josh",       last_name: "Cheek",      email: "demo+josh@jumpstartlab.com",   city: "Chicago",          state: "Illinois",     password: "password", role: "admin"},
  {first_name: "Jeff",       last_name: "Casimir",    email: "demo+jeff@jumpstartlab.com",   city: "Denver",           state: "Colorado",     password: "password", role: "user"},
  {first_name: "Emily",      last_name: "Davis",      email: "emilyadavis303@gmail.com",     city: "Denver",           state: "Colorado",     password: "password", role: "user"},
  {first_name: "Will",       last_name: "Faurot",     email: "will@email.com",               city: "Denver",           state: "Colorado",     password: "password", role: "user"},
  {first_name: "Gustavo",    last_name: "Villagrana", email: "gustavo@email.com",            city: "Austin",           state: "Texas",        password: "password", role: "user"},
  {first_name: "Marc",       last_name: "Garreau",    email: "marc@email.com",               city: "Orlando",          state: "Florida",      password: "password", role: "user"},
  {first_name: "Eric",       last_name: "Fransen",    email: "eric@email.com",               city: "St. Louis",        state: "Missouri",     password: "password", role: "user"},
  {first_name: "Davis",      last_name: "Developer",  email: "davis.developer303@gmail.com", city: "Vail",             state: "Colorado",     password: "password", role: "user"},
  {first_name: "Heather",    last_name: "Jackson",    email: "jackson@email.com",            city: "New York",         state: "New York",     password: "password", role: "user"},
  {first_name: "Nealey",     last_name: "Bell",       email: "nealey@email.com",             city: "Denver",           state: "Colorado",     password: "password", role: "user"},
  {first_name: "Noel",       last_name: "Worden",     email: "noel@email.com",               city: "Milwaukee",        state: "Wisconsin",    password: "password", role: "user"},
  {first_name: "Corey",      last_name: "Davis",      email: "corey@email.com",              city: "Denver",           state: "Colorado",     password: "password", role: "user"},
  {first_name: "Shannon",    last_name: "Combs",      email: "shannon@email.com",            city: "Chicago",          state: "Illinois",     password: "password", role: "user"},
  {first_name: "Jessica",    last_name: "Goulding",   email: "jessica@email.com",            city: "Basalt",           state: "Colorado",     password: "password", role: "user"},
  {first_name: "Alan",       last_name: "Smith",      email: "alan@email.com",               city: "Austin",           state: "Texas",        password: "password", role: "user"},
  {first_name: "Robert",     last_name: "Gu",         email: "robert@email.com",             city: "Washington",       state: "DC",           password: "password", role: "user"},
  {first_name: "Horacio",    last_name: "Chavez",     email: "horacio@email.com",            city: "San Diego",        state: "California",   password: "password", role: "user"},
  {first_name: "Hilary",     last_name: "Denton",     email: "hilary@email.com",             city: "Philadelphia",     state: "Pennsylvania", password: "password", role: "user"},
  {first_name: "Andrew",     last_name: "Watkins",    email: "watts@email.com",              city: "New York",         state: "New York",     password: "password", role: "user"},
  {first_name: "Chad",       last_name: "Brading",    email: "chad@email.com",               city: "Las Vegas",        state: "Nevada",       password: "password", role: "user"},
  {first_name: "Andy",       last_name: "Mention",    email: "andy@email.com",               city: "San Diego",        state: "California",   password: "password", role: "user"},
  {first_name: "Allison",    last_name: "Larson",     email: "allison@email.com",            city: "Chicago",          state: "Illinois",     password: "password", role: "user"},
  {first_name: "Jonmichael", last_name: "Chambers",   email: "jon@email.com",                city: "Denver",           state: "Colorado",     password: "password", role: "user"},
  {first_name: "Tan",        last_name: "Doan",       email: "tan@email.com",                city: "Denver",           state: "Colorado",     password: "password", role: "user"},
  {first_name: "Tim",        last_name: "Proctor",    email: "tim@email.com",                city: "Austin",           state: "Texas",        password: "password", role: "user"},
  {first_name: "Brittany",   last_name: "Parker",     email: "brittany@email.com",           city: "Carbondale",       state: "Colorado",     password: "password", role: "user"},
  {first_name: "Daniel",     last_name: "Lee",        email: "daniel@email.com",             city: "Glenwood Springs", state: "Colorado",     password: "password", role: "user"},
  {first_name: "Dez",        last_name: "Lee",        email: "dez@email.com",                city: "Glenwood Springs", state: "Colorado",     password: "password", role: "user"},
  {first_name: "Trever",     last_name: "Floyd",      email: "trever@email.com",             city: "Carbondale",       state: "Colorado",     password: "password", role: "user"}
])
